- name: installed packages
  command: rpm -qa
  register: installed_packages

- name: install packages
  sudo: yes
  yum:
    name: "{{ supervisor_rpm_url }}"
    state: present
    enablerepo: epel
  when: installed_packages.stdout.find('supervisor') == -1

- name: configure supervisord.conf
  sudo: yes
  ini_file:
    dest: /etc/supervisord.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - "{{ supervisor_default_settings }}"

- name: ensure restarted supervisord service
  sudo: yes
  service:
    name: supervisord
    state: restarted
    enabled: yes
